"""update create date table category

Revision ID: 95810a265313
Revises: bf60cfd1beb7
Create Date: 2024-06-20 15:44:23.340803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95810a265313'
down_revision = 'bf60cfd1beb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
